version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: erpnext
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnext123
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis-cache:
    image: redis:alpine
    restart: always
    volumes:
      - redis_cache_data:/data

  redis-queue:
    image: redis:alpine
    restart: always
    volumes:
      - redis_queue_data:/data

  redis-socketio:
    image: redis:alpine
    restart: always
    volumes:
      - redis_socketio_data:/data

  erpnext:
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=erpnext
      - DB_USER=erpnext
      - DB_PASSWORD=erpnext123
      - REDIS_CACHE_URL=redis://redis-cache:6379
      - REDIS_QUEUE_URL=redis://redis-queue:6379
      - REDIS_SOCKETIO_URL=redis://redis-socketio:6379
      - SOCKETIO_PORT=9000
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./apps:/home/frappe/frappe-bench/apps
      - ./logs:/home/frappe/frappe-bench/logs
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./sites:/var/www/html/sites
    depends_on:
      - erpnext

volumes:
  db_data:
  redis_cache_data:
  redis_queue_data:
  redis_socketio_data: