version: '3.8'

services:
  erpnext:
    image: frappe/erpnext:latest
    container_name: ithm-erpnext
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=erpnext
      - MARIADB_USER=erpnext
      - MARIADB_PASSWORD=erpnext
      - ERPNEXT_SITE_NAME=ithm.local
      - ERPNEXT_ADMIN_PASSWORD=admin
      - ERPNEXT_SITE_ADMIN=Administrator
    ports:
      - "8000:8000"
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
        bench --site ithm.local install-app erpnext &&
        bench --site ithm.local install-app education &&
        bench start
      "

  mariadb:
    image: mariadb:10.6
    container_name: ithm-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=erpnext
      - MARIADB_USER=erpnext
      - MARIADB_PASSWORD=erpnext
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    container_name: ithm-redis
    ports:
      - "6379:6379"

volumes:
  erpnext_data:
  erpnext_logs:
  mariadb_data:
