version: '3.8'

# Development overrides for docker-compose.yml
services:
  erpnext:
    environment:
      - DEVELOPER_MODE=1
      - DEBUG=1
    volumes:
      - ./apps:/home/frappe/frappe-bench/apps
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
      - ./config:/home/frappe/frappe-bench/config
    command: bash -c "bench start"
    
  # Additional development tools
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=cache:redis-cache:6379,queue:redis-queue:6379,socketio:redis-socketio:6379